
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_download_insecure=true
  config.ssh.insert_key = false
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.provision :docker
  config.vm.provision :docker_compose


  config.vm.define "server-1" do |ci|
    ci.vm.network "private_network" , ip: '192.168.33.60'
    ci.vm.hostname = "ciserver"
    ci.vm.provision :file, source:"../docker/docker-compose.ci.yml", destination:"docker-compose.yml"
    ci.vm.provision :docker_compose, yml:"/home/vagrant/docker-compose.yml", run: "always"
    ci.vm.provision "shell", inline: $script
    ci.vm.provision :shell, inline:"sudo chmod 777 /var/run/docker.sock"
  end
end
