
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_download_insecure=true
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "5096"
  end

  config.vm.provision :docker
  config.vm.provision :docker_compose


  config.vm.define "server-1" do |ci|
    ci.vm.network "private_network" , ip: '192.168.33.60'
    ci.vm.hostname = "ciserver"
    ci.vm.provision :file, source:"../docker/docker-compose.ci.yml", destination:"docker-compose.yml"
    ci.vm.provision :docker_compose, yml:"/home/vagrant/docker-compose.yml", run: "always"
    ci.vm.provision :shell, inline:"sudo chmod 777 /var/run/docker.sock"
  end

  config.vm.define "server-3" do |cd|
    cd.vm.network "private_network", ip: '192.168.56.62'
    cd.vm.hostname = "cdserver"
    cd.vm.provision :file, source:"../docker/docker-compose.cd.yml", destination:"docker-compose.cd.yml"
    cd.vm.provision :docker_compose, yml:"/home/vagrant/docker-compose.cd.yml", run: "always"
    cd.vm.provision :shell, inline:"sudo chmod 777 /var/run/docker.sock"
  end

  config.vm.define "server-2" do |server2|
    server2.vm.network "private_network" , ip: '192.168.33.61'
    server2.vm.hostname = "server2"
    server2.vm.provision "shell", inline: <<-SHELL
    #!/bin/bash
    sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
  SHELL
  end
end
