version: '3.7'
services:
  gocd_server:
    image: gocd/gocd-server:v22.2.0
    container_name: gocd_server
    restart: always
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - godata_server:/godata
      - go_server:/home/go

  gocd_agent_ubuntu:
    image: gocd/gocd-agent-ubuntu-20.04:v22.2.0
    container_name: gocd_agent_ubuntu
    restart: always
    depends_on:
      - gocd_server
    environment:
      - GO_SERVER_URL=http://gocd_server:8153/go
      #- AGENT_AUTO_REGISTER_KEY=
      - AGENT_AUTO_REGISTER_RESOURCES=ubuntu
      - AGENT_AUTO_REGISTER_HOSTNAME=gocd_agent_ubuntu
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  gocd_agent_docker:
    image: gocd/gocd-agent-docker-dind:v22.2.0
    container_name: gocd_agent_docker
    restart: always
    depends_on:
      - gocd_server
    environment:
      - GO_SERVER_URL=http://gocd_server:8153/go
      #- AGENT_AUTO_REGISTER_KEY=
      - AGENT_AUTO_REGISTER_RESOURCES=docker
      - AGENT_AUTO_REGISTER_HOSTNAME=gocd_agent_docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  gocd_agent_python:
    image: celestepalet/gocdpython
    container_name: gocd_agent_python
    restart: always
    depends_on:
      - gocd_server
    environment:
      - GO_SERVER_URL=http://gocd_server:8153/go
      #- AGENT_AUTO_REGISTER_KEY=
      - AGENT_AUTO_REGISTER_RESOURCES=python
      - AGENT_AUTO_REGISTER_HOSTNAME=gocd_agent_python
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  godata_server:
    name: godata_server
  go_server:
    name: go_server